version: '3'

networks:
  ipasta_net:
    name: ipasta_net
    driver: bridge

volumes:
  n_wp:
    driver: local
    name: n_wp
    driver_opts:
      type: none
      o: bind
      device: /home/ipasta/data/n_wp
  sql:
    driver: local
    name: sql
    driver_opts:
      type: none
      o: bind
      device: /home/ipasta/data/sql

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    env_file: .env
    volumes:
      - n_wp:/var/www/html
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: nginx
    ports:
      - "443:443"

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    env_file: .env
    volumes:
      - n_wp:/var/www/html
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: wordpress

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    env_file: .env
    volumes:
      - sql:/var/lib/mysql
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: mariadb

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    env_file: .env
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: adminer
#    ports:
#      - "5000:5000"

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    env_file: .env
    restart: always
    user: root
    networks:
      - ipasta_net

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    env_file: .env
    restart: always
    user: root
    volumes:
      - n_wp:/root
    networks:
      - ipasta_net
    ports:
      - "20:20"
      - "21:21"
      - "21000:21000"
  website:
    build: ./requirements/bonus/website
    image: website
    env_file: .env
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: website
    ports:
      - "8080:80"