version: '3'

networks:
  ipasta_net:
    name: ipasta_net
    driver: bridge

volumes:
  n_wp:
    driver: local
    name: n_wp
    driver_opts:
      type: none
      o: bind
      device: /home/ipasta/data/n_wp
  sql:
    driver: local
    name: sql
    driver_opts:
      type: none
      o: bind
      device: /home/ipasta/data/sql

services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - CERTS_CRT=${CERTS_CRT}
        - CERTS_KEY=${CERTS_KEY}
        - DOMAIN_GRAFANA=${DOMAIN_GRAFANA}
    image: nginx
    env_file: .env
    volumes:
      - n_wp:/var/www/html
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: nginx
    ports:
      - "443:443"
  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - CONT_MARIADB=${CONT_MARIADB}
        - WP_BASE=${WP_BASE}
        - CONT_REDIS=${CONT_REDIS}
    image: wordpress
    env_file: .env
    volumes:
      - n_wp:/var/www/html
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: wordpress
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - CONT_REDIS=${CONT_REDIS}
        - WP_BASE=${WP_BASE}
    image: mariadb
    env_file: .env
    volumes:
      - sql:/var/lib/mysql
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: mariadb
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    env_file: .env
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: adminer
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    env_file: .env
    restart: always
    user: root
    networks:
      - ipasta_net
  ftp:
    build:
      context: ./requirements/bonus/ftp
      args:
        - ROOT_PASSWORD=${ROOT_PASSWORD}
    image: ftp
    container_name: ftp
    env_file: .env
    restart: always
    user: root
    volumes:
      - n_wp:/root
    networks:
      - ipasta_net
    ports:
      - "21:21"
      - "21000:21000"
  website:
    build: ./requirements/bonus/website
    image: website
    env_file: .env
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: website
  grafana:
    build: ./requirements/bonus/grafana
    image: grafana
    env_file: .env
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: grafana
    