networks:
  ipasta_net:
    name: ipasta_net
    driver: bridge

volumes:
  n_wp:
    driver: local
    name: n_wp
    driver_opts:
      type: none
      o: bind
      device: /home/ipasta/inception_volumes/n_wp
  sql:
    driver: local
    name: sql
    driver_opts:
      type: none
      o: bind
      device: /home/ipasta/inception_volumes/sql

services:
  nginx:
    build: ./requirements/nginx
    env_file: .env
    volumes:
      - n_wp:/var/www/n_wp
    restart: always
    user: root #TODO это чего и зачем?
    networks:
      - ipasta_net
    container_name: nginx
    ports:
      - "443:443"

  wordpress:
    build: ./requirements/wordpress
    env_file: .env
#    volumes:
#      - n_wp:/var/www/n_wp
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: wordpress
#    ports:
#      - "9000:9000"

  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - n_wp:/var/www/sql
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: mariadb
#    ports:
#      - "3306:3306" #TODO переделать (наверное удалить)

  phpmyadmin:
    build: ./requirements/bonus/phpmyadmin
    env_file: .env
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: phpmyadmin
    ports:
      - "5000:5000"


