networks:
  ipasta_net:
    name: ipasta_net
    driver: bridge

volumes:
  n_wp:
    driver: local
    name: n_wp
    driver_opts:
      type: none
      o: bind
      device: /home/ipasta/data/n_wp
  sql:
    driver: local
    name: sql
    driver_opts:
      type: none
      o: bind
      device: /home/ipasta/data/sql

services:
  nginx:
    build: ./requirements/nginx
    env_file: .env
    volumes:
      - n_wp:/var/www/html
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: nginx
    ports:
      - "443:443"

  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - n_wp:/var/www/html
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: wordpress

  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - sql:/var/lib/mysql
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: mariadb

  phpmyadmin:
    build: ./requirements/bonus/phpmyadmin
    env_file: .env
    restart: always
    user: root
    networks:
      - ipasta_net
    container_name: phpmyadmin
    ports:
      - "5000:5000"


